security:
  key: "${mule.key}"

process:
  clientId: "replace-process-client-id"
  clientSecret: "replace-process-client-secret"
oms:
  username: "replace-oms-username"
  password: "replace-oms-password"
