# ========================
# oms-sapi - Secure QA
# ========================

security.key=${mule.key}

# OMS Backend Credentials
oms.backend.clientId=qa-oms-client-id-placeholder
oms.backend.clientSecret=qa-oms-client-secret-placeholder
