# ========================
# oms-sapi - Secure PROD
# ========================

security.key=${mule.key}

# OMS Backend Credentials
oms.backend.clientId=prod-oms-client-id-placeholder
oms.backend.clientSecret=prod-oms-client-secret-placeholder
