# ========================
# oms-sapi - Secure DEV
# ========================

security.key=${mule.key}

# OMS Backend Credentials
oms.backend.clientId=dev-oms-client-id-placeholder
oms.backend.clientSecret=dev-oms-client-secret-placeholder
