#%RAML 1.0 Library
usage: Data types for OMS System API (oms-sapi)

types:
  Error:
    type: object
    properties:
      code: string
      message: string
      correlationId?: string
      timestamp?: datetime
