security:
  key: "${mule.key}"

customer:
  clientId: "replace-customer-client-id"
  clientSecret: "replace-customer-client-secret"
inventory:
  clientId: "replace-inventory-client-id"
  clientSecret: "replace-inventory-client-secret"
payment:
  clientId: "replace-payment-client-id"
  clientSecret: "replace-payment-client-secret"
oms:
  clientId: "replace-oms-client-id"
  clientSecret: "replace-oms-client-secret"
shipping:
  clientId: "replace-shipping-client-id"
  clientSecret: "replace-shipping-client-secret"
