security:
  key: "${mule.key}"

customer:
  clientId: "replace-prod-customer-client-id"
  clientSecret: "replace-prod-customer-client-secret"
inventory:
  clientId: "replace-prod-inventory-client-id"
  clientSecret: "replace-prod-inventory-client-secret"
payment:
  clientId: "replace-prod-payment-client-id"
  clientSecret: "replace-prod-payment-client-secret"
oms:
  clientId: "replace-prod-oms-client-id"
  clientSecret: "replace-prod-oms-client-secret"
shipping:
  clientId: "replace-prod-shipping-client-id"
  clientSecret: "replace-prod-shipping-client-secret"
