security:
  key: "${mule.key}"

customer:
  clientId: "replace-qa-customer-client-id"
  clientSecret: "replace-qa-customer-client-secret"
inventory:
  clientId: "replace-qa-inventory-client-id"
  clientSecret: "replace-qa-inventory-client-secret"
payment:
  clientId: "replace-qa-payment-client-id"
  clientSecret: "replace-qa-payment-client-secret"
oms:
  clientId: "replace-qa-oms-client-id"
  clientSecret: "replace-qa-oms-client-secret"
shipping:
  clientId: "replace-qa-shipping-client-id"
  clientSecret: "replace-qa-shipping-client-secret"
