#%RAML 1.0 Library
usage: Traits for Payment System API (payment-sapi)

uses:
  payment-sapi-types: ../types/payment-sapi-types.raml

traits:
  responses-401:
    responses:
      401:
        body:
          application/json:
            type: payment-sapi-types.Error
            example: !include ../examples/error-401.json

  responses-500:
    responses:
      500:
        body:
          application/json:
            type: payment-sapi-types.Error
            example: !include ../examples/error-500.json
