# ========================
# shipping-sapi - Secure PROD
# ========================

security.key=${mule.key}

# Shipping Backend Credentials
shipping.backend.clientId=prod-shipping-client-id-placeholder
shipping.backend.clientSecret=prod-shipping-client-secret-placeholder
