# ========================
# shipping-sapi - Secure QA
# ========================

security.key=${mule.key}

# Shipping Backend Credentials
shipping.backend.clientId=qa-shipping-client-id-placeholder
shipping.backend.clientSecret=qa-shipping-client-secret-placeholder
