# ========================
# shipping-sapi - Secure DEV
# ========================

security.key=${mule.key}

# Shipping Backend Credentials
shipping.backend.clientId=dev-shipping-client-id-placeholder
shipping.backend.clientSecret=dev-shipping-client-secret-placeholder
