# ========================
# QA Secure Properties
# ========================

security.key=${mule.key}

# Payment Backend Credentials
payment.backend.clientId=QA_CLIENT_ID_PLACEHOLDER
payment.backend.clientSecret=QA_CLIENT_SECRET_PLACEHOLDER
