# ========================
# PROD Secure Properties
# ========================

security.key=${mule.key}

# Payment Backend Credentials
payment.backend.clientId=PROD_CLIENT_ID_PLACEHOLDER
payment.backend.clientSecret=PROD_CLIENT_SECRET_PLACEHOLDER
