# ========================
# DEV Secure Properties
# ========================

security.key=${mule.key}

# Payment Backend Credentials
payment.backend.clientId=DEV_CLIENT_ID_PLACEHOLDER
payment.backend.clientSecret=DEV_CLIENT_SECRET_PLACEHOLDER
